ReceiptScanner/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ReceiptScanner.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Session["User_Id"] == null)
            {
                ViewBag.errorMessage = "Login to see this page";
                return null;
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Index(FormCollection form)
        {
            HttpClient client = new HttpClient();
            var response = await client.PostAsync("https://vision.googleapis.com/v1/images:annotate?key=AIzaSyAAghI5eA0GCMLARpjSv8tp7HxB5cU28xg", new StringContent(form.ToString(), Encoding.UTF8, "application/json"));
            
            return Json(response);
        }
    }
}

ReceiptScanner/Controllers/ReceiptController.cs
using Newtonsoft.Json;
using ReceiptScanner.ContractResolvers;
using ReceiptScanner.DAL;
using ReceiptScanner.Models;
using ReceiptScanner.Models.EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ReceiptScanner.Controllers
{
    public class ReceiptController : Controller
    {
        // GET: Receipt
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Scan(string base64String)
        {
            var imageParts = base64String.Split(',').ToList<string>();
            byte[] imageBytes = Convert.FromBase64String(imageParts[1]);

            using (var client = new HttpClient())
            {
                GoogleVision googleVision = new GoogleVision()
                {
                    Requests = new List<Request>()
                    {
                        new Request()
                        {
                            Image = new Image()
                            {
                                Content = imageParts[1]
                            },

                            Features = new List<Feature>()
                            {
                                new Feature()
                                {
                                    Type = "TEXT_DETECTION"

                                }
                            },
                            ImageContext = new ImageContext()
                            {
                                LanguageHints = new List<string>()
                                {
                                    "da"
                                }
                            }
                        }
                    }
                };

                string uri = "https://vision.googleapis.com/v1/images:annotate?key=" + "AIzaSyAAghI5eA0GCMLARpjSv8tp7HxB5cU28xg";

                JsonSerializerSettings settings = new JsonSerializerSettings
                {
                    ContractResolver = new CamelCaseContractResolver(),
                    NullValueHandling = NullValueHandling.Ignore
                };

                string jsonRequest = JsonConvert.SerializeObject(googleVision, Formatting.None, settings);

                var response = await client.PostAsync(uri, new StringContent(jsonRequest, Encoding.UTF8, "application/json"));
                var content = response.Content.ReadAsStringAsync();

                return Json(data: content.Result);
            }
        }

        [HttpPost]
        public ActionResult Save(Receipt receipt)
        {
            //if (Session["User_Id"] == null || Session["Account_Id"] == null)

            if (Session["User_Id"] == null)
            {
                ViewBag.errorMessage = "Please login";
                return View("../User/Login");
            }
            var db = new DatabaseContext();
            db.Receipts.Add(
                new Receipt
                {
                    Name = receipt.Name,
                    Date = receipt.Date,
                    Content = receipt.Content,
                    Price = receipt.Price,
                    Category = receipt.Category,
                    Notes = receipt.Notes,
                    Base64_Image = receipt.Base64_Image,
                    //Currency_Id = receipt.Currency_Id,
                    //Account_Id = Convert.ToInt32(Session["Account_Id"]),
                    User_Id = Convert.ToInt32(Session["User_Id"])
                }
            );
            db.SaveChanges();
            return View(receipt);
        }
    }
}

ReceiptScanner/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ReceiptScanner/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ReceiptScanner/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@section Scripts {
    <script type="text/javascript" src="~/Scripts/scan.js"></script>
}

    <div class="row">
        <nav class="nav-menu col s12">
            <ul>
                <li>
                    <div class="input-field file">
                        <a class="btn-small" href="#">Gem kvittering</a>
                        <input type="file" accept="image/*" class="js-receipt-upload" />
                    </div>
                </li>
                <li>
                    <a class="btn-small" href="overview.html">Oversigt</a>
                </li>
                <li>
                    <a class="btn-small" href="#">Tilbud</a>
                </li>
                <li>
                    <a class="btn-small" href="#">Indstillinger</a>
                </li>
            </ul>
        </nav>
        <form action="@Url.Action("Save", "Receipt")" method="post" accept-charset="utf-8" class="receipt-information save col s12">
            <input type="text" name="Base64_Image" id="js-input-base64" hidden/>
            <img src="" class="receipt-preview" alt="">
            <div>
                <div class="input-field text inputjs">
                    <input type="text" name="Name">
                    <label for="Name">Navn</label>
                </div>
                <div class="input-field text inputjs">
                    <input type="text" name="Category">
                    <label for="Category">Kategori</label>
                </div>
                <div class="total-price">
                    <div class="input-field number inputjs">
                        <input type="number" name="Price" step="0.01">
                        <label for="Price">Total pris</label>
                    </div>
                    <div class="input-field select inputjs">
                        <select name="Currency_Id">
                            <option value="DKK" selected>DKK</option>
                        </select>
                        <label for="Currency_Id">Valuta</label>
                    </div>
                </div>
                <div class="input-field date inputjs">
                    <input type="date" name="Date">
                    <label for="Date">Dato</label>
                </div>
                <div class="input-field textarea inputjs">
                    <textarea name="Notes" rows="3" cols="30"></textarea>
                    <label for="Notes">Noter</label>
                </div>
                <div class="input-field textarea inputjs">
                    <textarea name="ContentPreview" rows="3" cols="30" disabled></textarea>
                    <input type="hidden" name="Content"/>
                    <label for="Content">Indhold</label>
                </div>
                <div class="input-field submit">
                    <input type="submit" value="Gem">
                </div>
            </div>

        </form>
        <canvas id="c" class="col12"></canvas>
        <img src="" id="prev" alt="">
        <img src="" id="prevRotated" alt="">
    </div>